name: built_redux
version: 7.5.11
description: A state management library written in dart that enforces immutability
homepage: https://github.com/davidmarne/built_redux
dependencies:
  build: ^1.6.0
  built_collection: ^5.0.0-nullsafety.0
  built_value: ^8.0.0-nullsafety.0
  source_gen: ^0.9.10+1
  test: ^1.16.0-nullsafety.13

dev_dependencies:
  build_runner: ^1.11.0
  build_test: ^1.3.2
  built_value_generator: ^8.0.0-nullsafety.0

environment:
  sdk: '>=2.12.0-0 <3.0.0'
